server:
  port: 8082
logging:
  level:
    root: ${ROOT_LOGGING_LEVEL:info}
#info:
#  app:
#    name: @project.name@
#    description: @project.description@
#    version: @project.version@
#    encoding: @project.build.sourceEncoding@
#    java:
#      version: @java.version@
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: swagger
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true